### ISSUE TITLE
导出onnx文件出错

### ISSUE THREAD

**Issue by Hbelief1998** [chenjianqu/Solov2-TensorRT-CPP#13]
您好，在执行您步骤中的
```
python onnx_exporter.py ../configs/solov2/solov2_light_448_r34_fpn_8gpu_3x.py ../weights/SOLOv2_light_R34.onnx --checkpoint ../checkpoints/SOLOv2_LIGHT_448_R34_3x.pth --shape 384 1152
```
出现下面的报错，请问您知道什么原因吗？
RuntimeError: Given groups=1, weight of size [256, 258, 3, 3], expected input[1, 260, 40, 40] to have 258 channels, but got 260 channels instead

后面我更换了权重文件，换成了SOLOv2_LIGHT_512_DCN_R50_3x，执行您的命令没有报错，但是没有找到对应的.onnx文件的输出，请问为什么呢？

**Comment by longlongzxl** [comment]
我也时以上错误~请问如何处理？

**Comment by chenjianqu** [comment]
Try a predefined model:[baidudisk](https://pan.baidu.com/s/1GNQROWqASUoyjUsFPGnRHg), fetch code:qdsm
