### ISSUE TITLE
编译的时候出现error: reference to ‘DeviceType’ is ambiguous 错误

### ISSUE THREAD

**Issue by longlongzxl** [chenjianqu/Solov2-TensorRT-CPP#14]
`/home/zhang/3drparty/libtorch/include/ATen/core/DeprecatedTypeProperties.h:37:3: error: reference to ‘DeviceType’ is ambiguous
   37 |   DeviceType device_type() const {
      |   ^~~~~~~~~~
`
请问这时为什么？

**Comment by chenjianqu** [comment]
see [this](https://github.com/chenjianqu/Tracking-Solov2-Deepsort/issues/2)
