### ISSUE TITLE
not use libtorch for deployment solov2 tensorrt?

### ISSUE THREAD

**Issue by jcyhcs** [chenjianqu/Solov2-TensorRT-CPP#2]
hi,professor:
is there any possible for deployment solov2 don't use libtorch? just use tensorrt deserialize api, then write some postprocess code? beacause it has fewer dependence, install libtorch on jetson isn't friendly!
for your build_model , it can create raw tensorrt engine , so the demo can just read it as file,and then create tensorrt context,then deploy,
so, please help!

**Comment by chenjianqu** [comment]
This is possible in theory, but libTorch is easier to implement.
