### ISSUE TITLE
compile error!

### ISSUE THREAD

**Issue by jcyhcs** [chenjianqu/Solov2-TensorRT-CPP#3]
hi,professor:
when i compile (build_model , i got error:
Solov2-TensorRT-CPP/InstanceSegment/common.h:388:9: error: ‘virtual nvinfer1::IBuilder::~IBuilder()’ is protected within this context
         delete obj;
         ^~~~~~
why? my enviroment:
nvidia jetson tx2 with jetpack4.5.1
tensorrt 7.1.3
please help!

**Comment by chenjianqu** [comment]
This is about the tensorrt version mismatch, try upgrading to TensorRt8 if possible.
